### ISSUE TITLE
WooCommerce 4.6.1 Bug Shop_manager  [woocommerce_rest_cannot_view error]

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-admin#5745]
@bambootb commented on [Sat Oct 24 2020](https://github.com/woocommerce/woocommerce/issues/28085)

Already post this issue to Wordpress.org support:
https://wordpress.org/support/topic/woocommerce_rest_cannot_view-error-with-woocommerce-to-4-6-1/#post-13575114

Step to replicate:
1. Log into a user with role “shop manager”
2. go to order page or any WooCommerce page
for example: [yoursite]/wp-admin/edit.php?post_type=shop_order
3. open inspector tools, then there will show the errors

Please see the screenshot attached:
https://monosnap.com/file/SqYYcIK0cTMDVRldLHliv6ZmGLLf32

Best,
T

---

@bambootb commented on [Tue Oct 27 2020](https://github.com/woocommerce/woocommerce/issues/28085#issuecomment-717714938)

Any update regarding to the issue? @mikejolley @claudiosanches 

---

@juliaamosova commented on [Thu Oct 29 2020](https://github.com/woocommerce/woocommerce/issues/28085#issuecomment-719035525)

Hi @bambootb,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![shop_manager](https://user-images.githubusercontent.com/19143190/97634511-3a00e900-1a0c-11eb-91fc-92c4d63e1446.jpg)

I think this is rather a `high` priority issue and something we should fix soonish. However, whoever is going to work on it, feel free to argue. 

---

@bambootb commented on [Sat Nov 07 2020](https://github.com/woocommerce/woocommerce/issues/28085#issuecomment-723427745)

@juliaamosova 
Is there any update regarding to the issue.

Thanks,
T

---

@roykho commented on [Wed Nov 25 2020](https://github.com/woocommerce/woocommerce/issues/28085#issuecomment-733917513)

This is specifically related to WC Admin so I am moving it there.

**Comment by hsingyuc** [comment]
I can't reproduce this issue on `main` but can reproduce it on an older version of WooCommerce Admin. These PR https://github.com/woocommerce/woocommerce-admin/pull/6577 and https://github.com/woocommerce/woocommerce-admin/pull/6365 may have fixed the issue.

**Comment by bambootb** [comment]
Can anyone please take it seriously about this issue??

**Comment by alexflorisca** [comment]
@bambootb @vitaminkdesign @dlackovic2 @felipelousantos any update on when this is likely to get resolved? There is a support ticket related to this that I'm following up on.

**Comment by delacruzdesign** [comment]
Fix problem with add capabilty "manage_options" to shop_manager rol.

`$role->add_cap( 'manage_options', true );`

**Comment by dlackovic2** [comment]
> Fix problem with add capabilty "manage_options" to shop_manager rol.
> 
> `$role->add_cap( 'manage_options', true );`

I wouldn't call that really a fix. I don't want to add this user this high capability as it is not required for sure.

**Comment by delacruzdesign** [comment]
I know it. But this solves the problem of continuous 403 errors. 

Also although it is not 100% safe, I use Adminize Plugin. If someone tries to access these areas through the url, Adminize does not allow it. 

As long as you use secure passwords for your Store Managers, there should be no problems. 

I think it is a solution simply as a preventive measure, until it is corrected. But this problem has been around for a long time and it doesn't seem to be solved.

**Comment by ilyasfoo** [comment]
I was able to reproduce this in WooCommerce 6.1.1. I think we should fix it soon.

**Comment by chihsuan** [comment]
Interesting...I was not able to reproduce this with WooCommerce 6.2.0. 🤔 

![Screen Shot 2022-02-09 at 16 15 46](https://user-images.githubusercontent.com/4344253/153153873-fba32228-817c-4ce4-bbc5-245c259bca9e.png)

**Comment by dlackovic2** [comment]
I can also confirm that in latest update 6.2.0. I am no longer having this issue. Strange that this wasn't mentioned in change log. Or maybe it was but I couldn't identify this bugfix.

**Comment by chihsuan** [comment]
@dlackovic2 Thanks for confirming! I also couldn't find the related change logs. 

@roykho It would be great if you can also check this on your site. 

I'll close this issue soon if no one is still encountering this with 6.2.0. 🙂

**Comment by roykho** [comment]
@chihsuan - so this wasn't my report. I just moved the issue here. So I would say if you can't replicate it in latest, go ahead and close it. Perhaps test this back to back with version 6.1.1 of Woo core and see if indeed this is the case.

**Comment by chihsuan** [comment]
> so this wasn't my report. I just moved the issue here. So I would say if you can't replicate it in latest, go ahead and close it.

@roykho Ah, I didn't notice that. Okay, I'm going to close this. Thanks for the reply!

**Comment by dlackovic2** [comment]
@chihsuan It appears that bug wasn't completely fixed unfortunately.
When I visit WC Home (/wp-admin/admin.php?page=wc-admin) as user with shop_manager role I am still getting those errors as you can see in screenshot.
![Snimka zaslona 2022-02-11 010223](https://user-images.githubusercontent.com/68977388/153517487-e28e4779-a104-4135-90af-caa05c70cc04.png)
Not critical as orders and products (which are working fine now), but still there shouldn't be insufficient permissions.

**Comment by chihsuan** [comment]
@dlackovic2 We will release `woocommerce-admin` v3.2.0 soon. Can you try it then and get back to us?  I found it's actually the latest WCA fixes this issue. Thanks!

**Comment by dlackovic2** [comment]
Sure @chihsuan, will let you know :)

**Comment by dlackovic2** [comment]
> @dlackovic2 We will release `woocommerce-admin` v3.2.0 soon. Can you try it then and get back to us? I found it's actually the latest WCA fixes this issue. Thanks!

@chihsuan Just letting you know that I tried `woocommerce-admin` v3.2.0 and it appears that it finally fixes all those issues I was getting. 👍

**Comment by chihsuan** [comment]
@dlackovic2 Awesome. Thanks for letting me know! 😄

**Comment by ant0nioli** [comment]
Hi, I'm using the Woocommerce Product Vendors official extension:

- https://woocommerce.com/products/product-vendors/

and I'm getting these errors when I am logged in as users having one of the followings extension's roles:

- wc_product_vendors_admin_vendor
- wc_product_vendors_manager_vendor

The errors shows upp in the Admin's Products List View.

Thank you.

**Comment by chihsuan** [comment]
Hi @ant0nioli Thanks for reporting this. It seems that it's an issue with "Woocommerce Product Vendors". Could you contact [WooCommerce support](https://woocommerce.com/my-account/create-a-ticket/) or fill a [new issue](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=1-bug-report.yml) here?
