### ISSUE TITLE
Product Attributes with <3 characters (like XL) not populating in Analytics Filters

### ISSUE THREAD

**Issue by splaquet** [woocommerce/woocommerce-admin#5868]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
One of our staff was trying to perform a filtered search for XL t-shirts in Analytics.  She found that the XL size was not populating, while all of the other sizes were populating (Small, Medium, Large, XXL, XXXL).  I was able to confirm this with her.

I was trying to demonstrate other methods of producing those results for her, so she could carry on with her work.  During that process, I said, "you'll have to type a minimum of 3 characters into the search field to yield results."

On that hunch, i tried renamed the XL attribute to Extra Large. VOILA!

**Expected behavior**
When searching for product attributes, the results should most likely start populating after 1 character is entered.  I understand and realize why you wouldn't want this result on the front end.  But, specifically on attributes, we have several of them that are 1 or 2 characters.

**Actual behavior**
XL did not appear in the Filter
Analytics > Orders > Filter > Attributes > Size > XL

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Search for a 2 character attribute in Analytics

**Screenshots**
XL
![Attributes-XL](https://user-images.githubusercontent.com/6146508/101693888-42ebce00-3a40-11eb-9706-9a3fab76f47b.png)
![Analytics-XL](https://user-images.githubusercontent.com/6146508/101693889-43846480-3a40-11eb-8c68-54c2ee76db68.png)

Extra Large
![Analytics-ExtraLarge](https://user-images.githubusercontent.com/6146508/101693903-47b08200-3a40-11eb-80e8-5ecf6e4ebec4.png)
![Attributes-ExtraLarge](https://user-images.githubusercontent.com/6146508/101693905-48491880-3a40-11eb-98de-0813d9bdd586.png)

**Comment by moon0326** [comment]
Hi, @splaquet Thank you for taking the time to report this bug. We really appreciate it. 

Unfortunately, I wasn't able to reproduce it.

I added a new attribute Size with XL and Large.

They show up when I search for them. Please refer to the following screenshots. Are there any other extra steps I need to follow? 


![Screen Shot 2020-12-17 at 3 33 02 PM](https://user-images.githubusercontent.com/4723145/102556372-98962b00-407d-11eb-8d95-97e09c27887c.jpg)


![Screen Shot 2020-12-17 at 3 33 09 PM](https://user-images.githubusercontent.com/4723145/102556394-a2b82980-407d-11eb-8b5a-e79727a73099.jpg)



Thank you!
Moon

**Comment by splaquet** [comment]
Very odd indeed.  I'm still noticing this issue on our end, but I'm now noticing additional issues.

1) If you notice in my screenshot, there's a difference with how (size **x**) is displayed in your search vs mine.

2) I know that we've sold Large sizes (if you notice the very bottom of the screenshot), but that's also not properly pulling up in the search.

...I might have found my issue.  I thought that the Woo-Admin was merged in with the main WooCommerce branch.  (as notifications presented to deactivate and remove Woo-Admin)   I'm not noticing that it appears that they still function as 2 different components (2 separate plugin installs).  Is that correct, and I should reinstall/activate Woo-Admin?

![image](https://user-images.githubusercontent.com/6146508/103557319-ffd71c00-4e80-11eb-8816-04c1781893e9.png)

**Comment by joshuatf** [comment]
@splaquet WooCommerce Admin will get packaged and bundled with WooCommerce periodically so typically updates found in WooCommerce Admin will be available in the next release or so in WooCommerce.

If you want to use the latest fixes and features, installing WooCommerce Admin as a plugin will use the installed plugin over the version included with WooCommerce.

Which version of WooCommerce are you currently using?  It sounds like this bug is resolved for you when WooCommerce Admin is installed and activated, but not when only WooCommerce is active, is that right?

**Comment by splaquet** [comment]
We currently have WooCommerce 4.8.0 installed.  {insert mind boggled}

I tried installing/activating the latest Woo-Admin on one of our networks and am still seeing the same results.  ...also worth noting, we're seeing the same results across 3 different WPMU networks.  I'd call it an isolated incident if this was only happening on one of our MU installs, but all 3 makes me think there's a possible plugin conflict.

I'll have to connect with our tech team and get back.  I'm not really sure how or what is happening, but we'll look into it.

**Comment by samueljseay** [comment]
I did some investigation on this, and I think I know whats going on here. This is a limitation (or bug) on our end.

The reason this problem happens right now, is that the terms fetched from the API is limited to 10. So @splaquet when you renamed that term to "Extra large" it appeared higher up in alphabetical order and thus was shown in the term list.

I'm thinking the best we could do right now is try not to limit the terms, but I think there is an upper limit on doing this of 100, which may still be a lot better experience than right now, but in future we may need to consider searching a larger range of results.

I'll go back to the team to see if they're happy with this solution and if so it'll be in an upcoming release. Thanks for raising this!
